### PR TITLE
Update project compatibility for build/test at Windows

### LINKED ISSUE #93: Investigate adding ability to build/test easily in Windows
I recently discovered it is not particularly easy to work on this project in Windows, due to the reliance on the Makefile to build the project.

It may be worth investigating the use of a platform independent alternative to Make. Grunt or Gulp would likely fill this need.

@josx, would you have any objection to a PR replacing the Makefile with one of the above options? I have some familiarity with both Grunt and Gulp, and don't have a preference for one over the other.

If the Makefile is needed for other things (i.e. CI), the Makefile could be updated to just call Grunt/Gulp task to avoid duplicating configuration of build steps.

### PR DESCRIPTION
**Pull request by berviantoleo**
Fix #93 

Example:

image

### CODE REVIEW

**Comment by berviantoleo** [comment]
I just realize there is warning about `prepublish`. How about we move this too become `prepublichOnly`?

image

**Comment by berviantoleo** [comment]
I also suggest to change the coverage report to `nyc` instead of `istanbul` (since they also suggest to change - https://www.npmjs.com/package/istanbul).

It will looks like this:

image

**Comment by josx** [comment]
You are right about Istanbul, please change it.
Also delete makefile file we dont need it anymore.

**Comment by berviantoleo** [comment]
> 
> 
> You are right about Istanbul, please change it.
> Also delete makefile file we dont need it anymore.

I've updated the PR. Thanks.

**Comment by josx** [comment]
Good work!

**Pull request merged**
