### PR TITLE
add global option "useMulti" for configuring bulk actions

### PR DESCRIPTION
**Pull request by loming**

### CODE REVIEW

**Comment by josx** [comment]
Thanks!

- I dont understand very well why we need to have a global var for this (just for knowing it), because depends on the service on the backend. Right now if you setup to service on backend with multi, i think will work. or not?

- Also tests are not passing, tests are not prepared for this new global option.

**Comment by loming** [comment]
Hi Josx,

Because FeathersJS set 'multi' to false by default. And the current code requires me to do manual config for all services I have used in react-admin ( my application have more than 15 services.. ), my FeathersJS client options doesn't looks nice that way :P

**Comment by josx** [comment]
Ok, you are right on having just one global var for that.
Please make tests pass, then i will merge the PR.

**Comment by loming** [comment]
I have added more test cases to cover the changes, thanks :)

**Pull request merged**
