### PR TITLE
Fix type another props should be not required

### LINKED ISSUE #161: Typescript error
ra-data-feathers@2.9.0

```js
import feathers from "@feathersjs/feathers"
import feathersRestClient from "@feathersjs/rest-client"
import auth from "@feathersjs/authentication-client"
import { restClient, authClient } from "ra-data-feathers"

const client = feathers()
  .configure(feathersRestClient("http://localhost:3030").fetch(window.fetch))
  .configure(
    auth({
      storage: window.localStorage,
    })
  )
const restClientOptions = {
  id: "_id", // In this example, the database uses '_id' rather than 'id'
  usePatch: true, // Use PATCH instead of PUT for updates
}

const authClientOptions = {
  authenticate: {
    // Options included in calls to Feathers client.authenticate
    strategy: "jwt", // The authentication strategy Feathers should use
  },
  storageKey: "feathers-jwt",
  logoutOnForbidden: false,
  permissionsField: "role", // Use the 'userroles' field on the JWT as the users role
  redirectTo: "/login", // Our example login form might be at '/signin', redirect here if AUTH_CHECK fails
}

const dataProvider = restClient(client, restClientOptions)
```

The last line generates an error:
```
Argument of type '{ id: string; usePatch: boolean; }' is not assignable to parameter of type '{ usePatch?: boolean | undefined; customQueryOperators?: string[] | undefined; useMulti?: boolean | undefined; id?: string | undefined; } & { [Key: string]: { id: string; }; }'.
  Type '{ id: string; usePatch: boolean; }' is not assignable to type '{ [Key: string]: { id: string; }; }'.
    Property 'id' is incompatible with index signature.
      Type 'string' is not assignable to type '{ id: string; }'.
```

### PR DESCRIPTION
**Pull request by berviantoleo**
Fix #161

### CODE REVIEW

**Comment by berviantoleo** [comment]
I'm not sure if this will enough, feel free to review this changes.

**Comment by josx** [comment]
Great work!

Comments on it:
- It is ok not move on node 12.x
- It seems `tsd` not using /test/types files ( i have changed a prop on test/types/index.test-d.ts to see if i got an error running `tsd` and nothing is happening)
- it seems that it is not checking last param well, Now type let you add any other prop with content, but it is not checking type. Example:   `resource: { id: 11 }` Should check id as string on resource, right?

**Comment by berviantoleo** [comment]
`It seems tsd not using /test/types files ( i have changed a prop on test/types/index.test-d.ts to see if i got an error running tsd and nothing is happening)`

How about know? I just change the rules and it show errors now.

`it seems that it is not checking last param well, Now type let you add any other prop with content, but it is not checking type. Example: resource: { id: 11 } Should check id as string on resource, right?`

Right, seems I am misunderstand about checking the resources id props. I've changed it now.

**Comment by josx** [comment]
Well done!

**Pull request merged**
