### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by berviantoleo**
Add types for typescript from javascript source

### CODE REVIEW

**Comment by berviantoleo** [comment]
Ah, I just realize, the source use `package-lock.json`, but in CI use yarn.

I need to move use yarn (?)

**Comment by jamesholcomb** [comment]
Is a release for this PR coming soon?

**Comment by josx** [comment]
After merging https://github.com/josx/ra-data-feathers/pull/156 I will release a new version.

**Comment by josx** [comment]
Done! [v2.9.0](https://www.npmjs.com/package/ra-data-feathers/v/2.9.0)

**Pull request merged**
